apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-predictor-deployment
  labels:
    app: prime-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime-predictor
  template:
    metadata:
      labels:
        app: prime-predictor
    spec:
      containers:
      - name: prime-predictor
        image: prime-predictor:latest
        ports:
        - containerPort: 80